title: Erik Nel # your name (or website title) here
logo: "/images/E&O-022.png?raw=true" # your photo (or logo) here
description: > # your text below (remove <br> elements if you don't need line breaks)
  I am a Data Scientist, BSc Data Science, with strong experience in Data visualization, Machine Learning, NLP, Computer Vision and Time Series Analysis. I am proficient in Python and SQL as well as Data Analysis tools such as Tableau, Pandas, Matplotlib, Seaborn and Dash. 
  <br><br>
  I am a quick learner and a collaborative team player who loves to think outside of the box. I am very enthusiastic about all things Data and love to learn any new skills. 
  <br><br>
  <a href="https://www.linkedin.com/in/erik-nel-597758210/">View My LinkedIn Profile</a>
  <a href="https://github.com/Erik-02">View My GitHub Profile</a>
  E-mail: eriknel95@gmail.com
  
remote_theme: pages-themes/minimal@v0.2.0
plugins:
- jekyll-remote-theme
