title: Erik Nel # your name (or website title) here
logo: "images/profile.png?raw=trueheight=50width=30" # your photo (or logo) here
description: > # your text below (remove <br> elements if you don't need line breaks)
  Junior Business Analyst. 
  BSc Data Science
  <br>
  I am a Business Analyst and Data Science enthusiast with experience in Data visualization, Machine Learning, Computer Vision and Time Series Analysis. 
  <br>
  <a href="https://www.linkedin.com/in/erik-nel-597758210/">View My LinkedIn Profile</a>
  <br>
  E-mail: eriknel95@gmail.com
  
remote_theme: pages-themes/minimal@v0.2.0
plugins:
- jekyll-remote-theme
